#!/usr/bin/env python3

import sys, os, signal, epics
from time import sleep
from termcolor import colored

import configparser
profile_configuration = configparser.ConfigParser(interpolation=None)
profile_configuration.read_file(open('epicsconfig.ini'))
pc = profile_configuration


sys.path.append('/home/xf06bm/.ipython/profile_common/BMMCommon/')
from optics.dcm_parameters import dcm_parameters
BMM_dcm = dcm_parameters()

from numpy import pi, sin, cos, arcsin, deg2rad

import redis
redis_host = 'xf06bm-ioc2'
rkvs = redis.Redis(host=redis_host, port=6379, db=0)

from dashboard_tools import heartbeat, strut, triangle, HBARC
from dashboard_tools import writeline, determine_reference, remaining
from dashboard_tools import rack_string, vac_string, temperature_string, valves_string, ln2_string


xrd = False
try:
    if sys.argv[1].lower() == 'xrd':
        xrd = True
except:
    pass

maintenance = False
try:
    if 'main' in sys.argv[1].lower():
        maintenance = True
except:
    pass





def signal_handler(sig, frame):
    print('\nQuitting cadashboard. Bye.')
    sys.exit(0)  
signal.signal(signal.SIGINT, signal_handler)


count = 0

## ----- various PVs and other scalars
i0     = epics.PV(pc.get('pvs', 'i0'))
it     = epics.PV(pc.get('pvs', 'it'))
if rkvs.get('BMM:Ir').decode('utf-8') == 'quadem':
    ir = epics.PV(pc.get('pvs', 'ir_ic'))
else:
    ir = epics.PV(pc.get('pvs', 'ir_quadem'))
iy     = epics.PV(pc.get('pvs', 'iy'))
#bicron       = epics.PV(pc.get('pvs', 'bicron'))
ring_current = epics.PV(pc.get('pvs', 'ring_current'))
sleep(0.25)
ring_connected = ring_current.connect()

if maintenance is False:
    bl           = epics.PV(pc.get('pvs', 'bl'))
    bmps         = epics.PV(pc.get('pvs', 'bmps'))
    sha          = epics.PV(pc.get('pvs', 'sha'))
    shb          = epics.PV(pc.get('pvs', 'shb'))

bragg        = epics.Motor(pc.get('motors', 'bragg'))
dcmx         = epics.Motor(pc.get('motors', 'dcmx'))
sample       = {'x'     : epics.Motor(pc.get('motors', 'sample_x')),
                'y'     : epics.Motor(pc.get('motors', 'sample_y')),
                'wheel' : epics.Motor(pc.get('motors', 'sample_wheel')),
                'garot' : epics.Motor(pc.get('motors', 'sample_garot')),
                'pitch' : epics.Motor(pc.get('motors', 'sample_pitch')),
                'ref'   : epics.Motor(pc.get('motors', 'sample_ref')),
                'refx'  : epics.Motor(pc.get('motors', 'sample_refx')),
                'det'   : epics.Motor(pc.get('motors', 'sample_det')),
}
vac          = [epics.PV(pc.get('pvs', 'vac0')),
                epics.PV(pc.get('pvs', 'vac1')),
                epics.PV(pc.get('pvs', 'vac2')),
                epics.PV(pc.get('pvs', 'vac3')),
                epics.PV(pc.get('pvs', 'vac4')),
                epics.PV(pc.get('pvs', 'vac5')),
                epics.PV(pc.get('pvs', 'vac6'))]

temperatures = [epics.PV(pc.get('pvs', 't0')),
                epics.PV(pc.get('pvs', 't1')),
                epics.PV(pc.get('pvs', 't2')),
                epics.PV(pc.get('pvs', 't3')),
                epics.PV(pc.get('pvs', 't4')),
                epics.PV(pc.get('pvs', 't5')),
                epics.PV(pc.get('pvs', 't6')),
                epics.PV(pc.get('pvs', 't7')),
                epics.PV(pc.get('pvs', 't8')),
                epics.PV(pc.get('pvs', 't9')),
                epics.PV(pc.get('pvs', 't10')),]

rackA1 = epics.PV(pc.get('pvs', 'rackA1'))
rackB1 = epics.PV(pc.get('pvs', 'rackB1'))
rackC1 = epics.PV(pc.get('pvs', 'rackC1'))
rackC2 = epics.PV(pc.get('pvs', 'rackC2'))
rackC3 = epics.PV(pc.get('pvs', 'rackC3'))

if maintenance is False:
    fe_valves    = [epics.PV(pc.get('pvs', 'fev0')),
                    epics.PV(pc.get('pvs', 'fev1')),
                    epics.PV(pc.get('pvs', 'fev2')),]
valves       = [epics.PV(pc.get('pvs', 'v0')),
                epics.PV(pc.get('pvs', 'v1')),
                epics.PV(pc.get('pvs', 'v2')),
                epics.PV(pc.get('pvs', 'v3')),
                epics.PV(pc.get('pvs', 'v4')),
                epics.PV(pc.get('pvs', 'v5')), ]
ln2 = epics.PV(pc.get('pvs', 'ln2'))

if xrd is True:
    delta         = epics.Motor(pc.get('motors', 'delta'))
    eta           = epics.Motor(pc.get('motors', 'eta'))
    chi           = epics.Motor(pc.get('motors', 'chi'))
    phi           = epics.Motor(pc.get('motors', 'phi'))
    mu            = epics.Motor(pc.get('motors', 'mu'))
    nu            = epics.Motor(pc.get('motors', 'nu'))

slits         = [epics.Motor(pc.get('motors', 'slits_o')),
                 epics.Motor(pc.get('motors', 'slits_i')),
                 epics.Motor(pc.get('motors', 'slits_t')),
                 epics.Motor(pc.get('motors', 'slits_b'))]

try:
    linkam = epics.PV(pc.get('pvs', 'linkam'))
except:
    linkam = None
try:
    lakeshore = epics.PV(pc.get('pvs', 'lakeshore'))
except:
    lakeshore = None

    



print('\n')
waiting = True
while waiting:

    count += 1
    hcount = count % len(heartbeat)
    #xrd = False
    #if m2.vert < 0 and m2.pitch > 3:
    #    xrd = True
    
    ## ----- shutters and ring current
    if maintenance is True:
        bl_show = colored('Dis', 'red', attrs=['bold'])
        bmps_show = colored('BMPS', 'red', attrs=['bold'])
        sha_show = colored('A shutter', 'red', attrs=['bold'])
        shb_show = colored('B shutter', 'red', attrs=['bold'])
    else:
        if bl.get() == 0:
            bl_show = colored('Dis', 'white', attrs=['dark'])
        else:
            bl_show = colored('Ena', 'green', attrs=['bold'])

        if bmps.get() == 0:
            bmps_show = colored('BMPS', 'white', attrs=['dark'])
        else:
            bmps_show = colored('BMPS', 'green', attrs=['bold'])

        if sha.get() == 1:
            sha_show = colored('A shtr', 'white', attrs=['dark'])
        else:
            sha_show = colored('A shtr', 'green', attrs=['bold'])

        if shb.get() == 1:
            shb_show = colored('B shtr', 'white', attrs=['dark'])
        else:
            shb_show = colored('B shtr', 'green', attrs=['bold'])

    if maintenance is True:
        ring_show = colored(' maint ', 'magenta', attrs=None)
    else:
        if ring_connected is False:
            ring_show = colored('  ???   ', 'magenta', attrs=None)
        else:
            try:
                if ring_current.get() > 100:
                    ring_show = colored('%5.1f mA' % ring_current.get(), 'cyan', attrs=None)
                else:
                    ring_show = colored('%5.1f mA' % ring_current.get(), 'cyan', attrs=None)
            except:
                    ring_show = colored('  ???   ', 'red', attrs=None)

    ## ----- ion chamber signals
    def icsig(sig):
        try:
            val = sig.get()*10**9
        except:
            val = 0
        return val
    i0val = icsig(i0)
    itval = icsig(it)
    irval = icsig(ir)
    iyval = icsig(iy)
    
    ## ----- current time for time updates
    scan =     colored('   idle   ', 'grey', 'on_white')
    scantype = rkvs.get('BMM:scan:type').decode('utf-8')
    if xrd:
        scan = colored('not in use', 'grey', 'on_white')
        scantype = 'idle'
    else:
        ## ----- type of scan (xafs | line | area | time)
        if scantype == 'xafs':
            backdrop = 'on_magenta'
        elif scantype == 'line':
            backdrop = 'on_cyan'
        elif scantype == 'area':
            backdrop = 'on_yellow'
        elif scantype == 'time':
            backdrop = 'on_blue'
    if scantype != 'idle':
        scan = colored(f'{scantype} scan {remaining():<27}', 'white', backdrop)
            
    ## ----- update the energy
    if dcmx.RBV < 10:
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_111*sin(deg2rad(bragg.RBV)))
    else:
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_311*sin(deg2rad(bragg.RBV)))
    
    ## ----- update the display
    if xrd is False:
        thisinst = rkvs.get('BMM:automation:type').decode('utf-8')
        if 'glancing' in thisinst.lower():
            instrument = 'spnnr'
            cur = sample['garot'].RBV % 360
            slot = (9-round(cur/45)) % 8
            if slot == 0: slot = 8
        elif 'linkam' in thisinst.lower():
            instrument = 'lnkam'
            if linkam is None:
                slot = 0.0
            else:
                try:
                    slot = linkam.get()
                except:
                    slot = 0.0
            if slot is None: slot = 0.0
            slot = f'{slot:.1f}'
        elif 'lakeshore' in thisinst.lower():
            instrument = 'dsplx'
            if lakeshore is None:
                slot = 0
            else:
                slot = lakeshore.get()
        else:
            instrument = 'wheel'
            slot = round((15+sample['wheel'].RBV) / (-15)) % 24
            if slot == 0: slot = 24
        ref = determine_reference(sample)
        
        def bright(txt):
            return colored(txt, 'white', attrs=['bold'])
        def cyan(txt):
            return colored(txt, 'cyan', attrs=['bold'])

        ## --- top line: shutters, indicators for racks, temps, valves, vacuum
        rs  = rack_string((rackA1, rackB1,rackC1, rackC2, rackC3))
        vs  = vac_string(vac)
        ts  = temperature_string(temperatures)
        lns = ln2_string(ln2)
        vas = valves_string(fe_valves, valves, maintenance)
        shutters = f'[{bl_show}] [{bmps_show}] [{sha_show}] [{shb_show}]'
        line1 = f"{shutters} {bright('Racks')}: {rs} {strut} {bright('Vac')}: {vs} {strut} {bright('TC')}: {ts} {strut} {bright('GV')}: {vas}  {lns}\n"

        ## --- middle line: mono, element/edge, ion chambers, scan timer
        el  = colored(rkvs.get('BMM:pds:element').decode('utf-8'), 'yellow', attrs=['bold'])
        ed  = colored(rkvs.get('BMM:pds:edge').decode('utf-8'), 'yellow', attrs=['bold'])
        i0s = colored('I0', 'white', attrs=['bold']) + f':{i0val:8.3f} nA '
        its = colored('It', 'white', attrs=['bold']) + f':{itval:8.3f} nA '
        irs = colored('Ir', 'white', attrs=['bold']) + f':{irval:8.3f} nA '
        iys = colored('Iy', 'white', attrs=['bold']) + f':{iyval:8.3f} nA  '
        if int(rkvs.get('BMM:Iy')) == 0:
            line2 = f"{bright('mono')}: {cyan('%7.1f eV' % current_energy)} {strut} {el} {ed} {strut} Ring: {ring_show} {strut} {i0s} {its} {irs} {strut} {bright('XAS')} {scan}\n"
        else:
            line2 = f"{bright('mono')}: {cyan('%7.1f eV' % current_energy)} {strut} {el} {ed} {strut} Ring: {ring_show} {strut} {i0s} {its} {irs} {iys} {strut} {bright('XAS')} {scan}\n"
            
        ## --- bottom line: sample stages, heartbeat
        posX  = f" X: {sample['x'].RBV:7.3f} |"
        posY  = f" Y: {sample['y'].RBV:7.3f} |"
        posP  = f"pitch: {sample['pitch'].RBV:7.3f} |"
        posD  = f"det: {sample['det'].RBV:5.1f} |"
        slH   = slits[0].RBV-slits[1].RBV
        slV   = slits[2].RBV-slits[3].RBV
        hb    = colored(heartbeat[hcount], 'yellow')
        line3 = colored('Sample '+triangle, 'yellow', attrs=['bold']) + f'{posX}{posY} {posP} Ref: {ref}  | {posD} slits: {slH:5.2f} x{slV:5.2f} | {instrument} {slot:<6}                     {hb} '

        writeline(line1+line2+line3)

        sleep(1.0)

        ## check connection to ring current every 5-ish minutes. 
        if count % 300 == 0:
            count = 0
            ring_connected = ring_current.connect()



    
    ### XRD ###        
    else:
        #                 shutters        current       vacuum, temperatures, gate valves
        template = " [%s] [%s] [%s] [%s]  ring: %s  %s  %s: %s %s %s: %s %s %s: %s" + \
                   "\n %s: %s  %s  %s: %6d counts                                                                        %s: %s" + \
                   "\n %s %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f            %s"
        try:
            writeline(template  %
                      (bl_show, bmps_show, sha_show, shb_show, ring_show, strut,
                       colored('Vac', 'white', attrs=['bold']), vac_string(), strut,
                       colored('TC', 'white', attrs=['bold']), temperature_string(), strut,
                       colored('GV', 'white', attrs=['bold']), valves_string(),

                       colored('mono', 'white', attrs=['bold']), colored('%.1f eV' % current_energy, 'cyan', attrs=['bold']), strut,
                       colored('Bicron', 'white', attrs=['bold']), int(bicron.get()),
                       colored('XAS',  'white', attrs=['bold']), scan,
                   
                       colored('Goniometer '+triangle, 'yellow', attrs=['bold']),
                       u'\u03B4', delta.RBV,
                       u'\u03B7', eta.RBV,
                       u'\u03C7', chi.RBV,
                       u'\u03C6', phi.RBV,
                       u'\u03BC', mu.RBV,
                       u'\u03BD', nu.RBV,

                       heartbeat[hcount]
                   ))
        except:
            pass
        sleep(1.0)
 
