#!/usr/bin/env python3

import sys, os, signal, epics
from time import sleep
from termcolor import colored

# use the same monochromator parameters as the bsui profiles
sys.path.append('/home/xf06bm/.ipython/bmm_tools/src/')
from bmm_tools.optics.dcm_parameters import dcm_parameters
BMM_dcm = dcm_parameters()

from numpy import pi, sin, cos, arcsin, deg2rad


from dashboard_tools import red, white, magenta, dark, yellow, cyan, green
from dashboard_tools import heartbeat, strut, triangle, HBARC
from dashboard_tools import writeline, determine_reference, remaining
from dashboard_tools import rack_string, vac_string, temperature_string, valves_string, ln2_string, di_string

from dashboard_epics import rkvs, maintenance
from dashboard_epics import *   # all motor and signal PVs


xrd = False
try:
    if sys.argv[1].lower() == 'xrd':
        xrd = True
except:
    pass

def signal_handler(sig, frame):
    print('\nQuitting cadashboard. Bye.')
    sys.exit(0)  
signal.signal(signal.SIGINT, signal_handler)

count = 0

    
## game plan:
##
## on each loop gather up text tokens for each of the things to be displayed in the
## dashboard. Each of these tokens gets colored according to its state.
## These tokens are then concatinated into a three-line message that gets
## redisplayed every second

print('\n')
waiting = True
while waiting:

    count += 1
    hcount = count % len(heartbeat)
    #xrd = False
    #if m2.vert < 0 and m2.pitch > 3:
    #    xrd = True
    
    ## ----- text tokens for shutters and beamline enabled state
    if maintenance is True:     #  in maintenance mode
        bl_show   = red('Dis')
        bmps_show = red('BMPS')
        sha_show  = red('A shutter')
        shb_show  = red('B shutter')
    else:                       # else display green for open, gray for closed
        bl_show   = dark('Dis')    if bl.get()   == 0 else green('Ena')
        bmps_show = dark('BMPS')   if bmps.get() == 0 else green('BMPS')
        sha_show  = dark('A shtr') if sha.get()  == 1 else green('A shtr')
        shb_show  = dark('B shtr') if shb.get()  == 1 else green('B shtr')

    ## ----- text token for ring current
    if maintenance is True:
        ring_show = magenta(' maint ')
    else:
        if ring_connected is False:
            ring_show = magenta('  ???   ')
        else:
            try:
                if ring_current.get() > 100:
                    ring_show = cyan('%5.1f mA' % ring_current.get())
                else:
                    ring_show = cyan('%5.1f mA' % ring_current.get())
            except:
                    ring_show = red('  ???   ')

    ## ----- text tokens for ion chamber signals
    def icsig(sig):
        try:
            val = sig.get()*10**9
        except:
            val = 0
        return val
    i0val = icsig(i0)
    itval = icsig(it)
    irval = icsig(ir)
    iyval = icsig(iy)
    
    ## ----- current time for time updates
    scan =     colored('   idle   ', 'grey', 'on_white')
    scantype = rkvs.get('BMM:scan:type').decode('utf-8')
    if xrd:
        scan = colored('not in use', 'grey', 'on_white')
        scantype = 'idle'
    else:
        ## ----- type of scan (xafs | line | area | time)
        if scantype == 'xafs':
            backdrop = 'on_magenta'
        elif scantype == 'line':
            backdrop = 'on_cyan'
        elif scantype == 'area':
            backdrop = 'on_yellow'
        elif scantype == 'time':
            backdrop = 'on_blue'
        elif scantype == 'XRR ':
            backdrop = 'on_green'
        elif scantype != 'idle':
            backdrop = 'on_black'
    if scantype != 'idle':
        scan = colored(f'{scantype} scan {remaining():<27}', 'white', backdrop)
            
    ## ----- update the energy
    if dcmx.RBV < 10:
        # 111 monochromator in use, we know this because dcm.x is at a position less than 10 
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_111*sin(deg2rad(bragg.RBV)))
    else:
        # 311 monochromator in use, we know this because dcm.x is at a position greater than 10 
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_311*sin(deg2rad(bragg.RBV)))
    
    ## ----- update the display
    if xrd is False:
        thisinst = rkvs.get('BMM:automation:type').decode('utf-8')
        if 'glancing' in thisinst.lower():
            instrument = 'spnnr'
            cur = sample['garot'].RBV % 360
            slot = (9-round(cur/45)) % 8
            if slot == 0: slot = 8
        elif 'linkam' in thisinst.lower():
            instrument = 'lnkam'
            if linkam is None:
                slot = 0.0
            else:
                try:
                    slot = linkam.get()
                except:
                    slot = 0.0
            if slot is None: slot = 0.0
            slot = f'{slot:.1f}'
        elif 'lakeshore' in thisinst.lower():
            instrument = 'dsplx'
            if lakeshore is None:
                slot = 0
            else:
                slot = lakeshore.get()
        else:
            instrument = 'wheel'
            slot = round((-15+sample['wheel'].RBV) / (-15)) % 24
            if slot == 0: slot = 24
        ref = determine_reference(sample)
        
        ## --- top line: shutters, indicators for racks, temps, valves, vacuum
        rs  = rack_string((rackA1, rackB1,rackC1, rackC2, rackC3))
        vs  = vac_string(vac)
        ts  = temperature_string(temperatures)
        lns = ln2_string(ln2)
        dis = di_string(dia, dib)
        vas = valves_string(fe_valves, valves, maintenance)
        shutters = f'[{bl_show}] [{bmps_show}] [{sha_show}] [{shb_show}]'
        line1 = f"{shutters} {white('Racks')}: {rs} {strut} {white('Vac')}: {vs} {strut} {white('TC')}: {ts} {strut} {white('GV')}: {vas} {strut} {dis} {lns}\n"

        ## --- middle line: mono, element/edge, ion chambers, scan timer
        el  = yellow(rkvs.get('BMM:pds:element').decode('utf-8'))
        ed  = yellow(rkvs.get('BMM:pds:edge').decode('utf-8'))
        i0s = white('I0') + f':{i0val:8.3f} nA '
        its = white('It') + f':{itval:8.3f} nA '
        irs = white('Ir') + f':{irval:8.3f} nA '
        iys = white('Iy') + f':{iyval:8.3f} nA  '
        if int(rkvs.get('BMM:Iy')) == 0:
            line2 = f"{white('mono')}: {cyan('%7.1f eV' % current_energy)} {strut} {el} {ed} {strut} Ring: {ring_show} {strut} {i0s} {its} {irs} {strut} {white('XAS')} {scan}\n"
        else:
            line2 = f"{white('mono')}: {cyan('%7.1f eV' % current_energy)} {strut} {el} {ed} {strut} Ring: {ring_show} {strut} {i0s} {its} {irs} {iys} {strut} {white('XAS')} {scan}\n"
            
        ## --- bottom line: sample stages, heartbeat
        posX  = f" X: {sample['x'].RBV:7.3f} |"
        posY  = f" Y: {sample['y'].RBV:7.3f} |"
        posP  = f"pitch: {sample['pitch'].RBV:7.3f} |"
        posD  = f"det: {sample['det'].RBV:5.1f} |"
        slH   = slits[0].RBV-slits[1].RBV
        slV   = slits[2].RBV-slits[3].RBV
        hb    = yellow(heartbeat[hcount])
        line3 = yellow('Sample '+triangle) + f'{posX}{posY} {posP} Ref: {ref}  | {posD} slits: {slH:5.2f} x{slV:5.2f} | {instrument} {slot:<6}                     {hb} '

        writeline(line1+line2+line3)

        sleep(1.0)

        ## check connection to ring current every 5-ish minutes. 
        if count % 300 == 0:
            count = 0
            ring_connected = ring_current.connect()



    
    ### XRD ###        
    else:
        #                 shutters        current       vacuum, temperatures, gate valves
        template = " [%s] [%s] [%s] [%s]  ring: %s  %s  %s: %s %s %s: %s %s %s: %s" + \
                   "\n %s: %s  %s  %s: %6d counts                                                                        %s: %s" + \
                   "\n %s %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f | %s: %8.3f            %s"
        try:
            writeline(template  %
                      (bl_show, bmps_show, sha_show, shb_show, ring_show, strut,
                       white('Vac'), vac_string(), strut,
                       white('TC'), temperature_string(), strut,
                       white('GV'), valves_string(),

                       white('mono'), cyan('%.1f eV' % current_energy), strut,
                       white('Bicron'), int(bicron.get()),
                       white('XAS'), scan,
                   
                       yellow('Goniometer '+triangle),
                       u'\u03B4', delta.RBV,
                       u'\u03B7', eta.RBV,
                       u'\u03C7', chi.RBV,
                       u'\u03C6', phi.RBV,
                       u'\u03BC', mu.RBV,
                       u'\u03BD', nu.RBV,

                       heartbeat[hcount]
                   ))
        except:
            pass
        sleep(1.0)
 
