[services]
nsls2_redis = xf06bm-bmm-redis1.nsls2.bnl.gov
redis_port  = 6380
redis_ssl   = True
# database numbers for XAS RE.md, XRD RE.md, and storage of BMM state information
xas_redis   = 1
xrd_redis   = 2
bmm_redis   = 3


[motors]
# essential XAS stages
bragg        = XF:06BMA-OP{Mono:DCM1-Ax:Bragg}Mtr
dcmx         = XF:06BMA-OP{Mono:DCM1-Ax:X}Mtr
sample_x     = XF:06BM-ES{MC:09-Ax:6}Mtr
sample_y     = XF:06BM-ES{MC:09-Ax:7}Mtr
sample_wheel = XF:06BMA-BI{XAFS-Ax:RotB}Mtr
sample_garot = XF:06BMA-BI{XAFS-Ax:Mtr8}Mtr
sample_pitch = XF:06BMA-BI{XAFS-Ax:Roll}Mtr
sample_ref   = XF:06BMA-BI{XAFS-Ax:Ref}Mtr
sample_refx  = XF:06BMA-BI{XAFS-Ax:RefX}Mtr
sample_det   = XF:06BMA-BI{XAFS-Ax:Tbl_XD}Mtr

# essential XRD stages
delta   = XF:06BM-ES{SixC-Ax:VTTH}Mtr
eta     = XF:06BM-ES{SixC-Ax:VTH}Mtr
chi     = XF:06BM-ES{SixC-Ax:CHI}Mtr
phi     = XF:06BM-ES{SixC-Ax:PHI}Mtr
mu      = XF:06BM-ES{SixC-Ax:HTH}Mtr
nu      = XF:06BM-ES{SixC-Ax:HTTH}Mtr
slits_o = XF:06BM-BI{Slt:02-Ax:O}Mtr
slits_i = XF:06BM-BI{Slt:02-Ax:I}Mtr
slits_t = XF:06BM-BI{Slt:02-Ax:T}Mtr
slits_b = XF:06BM-BI{Slt:02-Ax:B}Mtr

[pvs]
# ion chambers & Bicron
i0        = XF:06BM-BI{IC:0}EM180:Current1:MeanValue_RBV
it        = XF:06BM-BI{IC:1}EM180:Current1:MeanValue_RBV
ir_ic     = XF:06BM-BI{EM:1}EM180:Current3:MeanValue_RBV
ir_quadem = XF:06BM-BI{IC:3}EM180:Current1:MeanValue_RBV
iy        = XF:06BM-BI{EM:1}EM180:Current4:MeanValue_RBV
bicron    = XF:06BM-ES:1{Sclr:1}.S25

# If on quadEM:  XF:06BM-BI{EM:1}EM180:Current2:MeanValue_RBV   

# storage ring, shutters
ring_current = SR:OPS-BI{DCCT:1}I:Real-I
bl           = SR:C06-EPS{PLC:1}Sts:BM_BE_Enbl-Sts
bmps         = SR:C06-EPS{PLC:1}Sts:BM_BMPS_Opn-Sts
sha          = XF:06BM-PPS{Sh:FE}Pos-Sts
shb          = XF:06BM-PPS{Sh:A}Pos-Sts


# rack temperatures
rackA1 = XF:06BM-CT{RG:A1-RTC:1}T-I
rackB1 = XF:06BM-CT{RG:B1-RTC:1}T-I
rackC1 = XF:06BM-CT{RG:C1-RTC:1}T-I
rackC2 = XF:06BM-CT{RG:C2-RTC:1}T-I
rackC3 = XF:06BM-CT{RG:C3-RTC:1}T-I

# vacuum guages
vac0 = XF:06BMA-VA{FS:1-CCG:1}P:Raw-I
vac1 = XF:06BMA-VA{Mono:DCM-CCG:1}P:Raw-I
vac2 = XF:06BMA-VA{FS:2-CCG:1}P:Raw-I
vac3 = XF:06BMA-VA{Mir:2-CCG:1}P:Raw-I
vac4 = XF:06BMA-VA{Mir:3-CCG:1}P:Raw-I
vac5 = XF:06BMB-VA{BT:1-CCG:1}P:Raw-I
vac6 = XF:06BMB-VA{FS:3-CCG:1}P:Raw-I


# various temerature sensors, not the racks
t0  = XF:06BMA-OP{Mono:DCM-Crys:1}T-I-I
t1  = XF:06BMA-OP{Mono:DCM-Crys:2}T-I-I
t2  = XF:06BMA-OP{Mono:DCM-Crys:1-Ax:R}T-I-I
t3  = XF:06BMA-OP{Mono:DCM-Crys:2-Ax:P}T-I-I
t4  = XF:06BMA-OP{Mono:DCM-Crys:2-Ax:R}T-I-I
t5  = XF:06BMA-OP{Mono:DCM-Crys:2-Ax:Perp}T-I-I
t6  = XF:06BMA-OP{Mono:DCM-Crys:2-Ax:Para}T-I-I
t7  = XF:06BMA-OP{Mir:2}T:1-I-I
t8  = XF:06BMA-OP{Mir:2}T:2-I-I
t9  = XF:06BMA-OP{Mir:3}T:1-I-I
t10 = XF:06BMA-OP{Mir:3}T:2-I-I

# front-end and beamline gate valves, LN2 valve
fev0 = FE:C06B-VA{GV:1}DB:Pos-Sts
fev1 = FE:C06B-VA{GV:2}DB:Pos-Sts
fev2 = FE:C06B-VA{GV:3}DB:Pos-Sts
v0   = XF:06BMA-VA{FS:1-GV:1}Pos-Sts
v1   = XF:06BMA-VA{BS:PB-GV:1}Pos-Sts
v2   = XF:06BMA-VA{FS:2-GV:1}Pos-Sts
v3   = XF:06BMA-VA{Mir:2-GV:1}Pos-Sts
v4   = XF:06BMA-VA{Mir:3-GV:1}Pos-Sts
v5   = XF:06BMB-VA{BT:1-GV:1}Pos-Sts
ln2  = XF:06BM-PU{LN2-Main:IV}Pos-Sts

# DI flow rate in the FOE
dia  = XF:06BM-PPS{DI}F:A1-I
dib  = XF:06BM-PPS{DI}F:B1-I

# instrument temperatures
linkam    = XF:06BM-ES:{LINKAM}:TEMP
lakeshore = XF:06BM-BI{LS:331-1}:SAMPLE_A
